### ISSUE TITLE
AJP request sends attributes incorrectly

### ISSUE THREAD

**Issue by stuartwdouglas** [espenhw/ajp-client#1]
https://github.com/espenhw/ajp-client/blob/master/src/main/java/org/grumblesmurf/ajp/ForwardRequestMessage.java#L131

The attribute code should be a single byte, not a 16 bit integer. This only works because tomcat will ignore unknown codes by default.

**Comment by espenhw** [comment]
Well spotted.  However, I neither use nor maintain this library any longer.  You're better off using https://github.com/hllhll/libajp13 instead.
